//! Генератор x86-64 ассемблерного кода из IR

use crate::ir::{FunctionIR, IRInstruction, Operand, ProgramIR};
use std::collections::HashMap;

pub struct X86Generator {
    string_counter: usize,
    string_literals: Vec<(String, String)>,
    label_counter: usize,
    var_offsets: HashMap<String, i32>,
    stack_size: usize,
}

impl X86Generator {
    pub fn new() -> Self {
        Self {
            string_counter: 0,
            string_literals: Vec::new(),
            label_counter: 0,
            var_offsets: HashMap::new(),
            stack_size: 0,
        }
    }

    pub fn generate(&mut self, program: &ProgramIR) -> super::CodegenResult {
        let mut output = String::new();

        self.label_counter = 0;
        self.string_counter = 0;
        self.string_literals.clear();

        output.push_str("; Generated by Mini Compiler (Sprint 5)\n");
        output.push_str("; Architecture: x86-64, ABI: System V AMD64\n\n");

        output.push_str("section .text\n");
        output.push_str("global main\n");
        output.push_str("global _start\n\n");

        for func in &program.functions {
            output.push_str(&self.generate_function(func));
            output.push_str("\n");
        }

        output.push_str("_start:\n");
        output.push_str("    call main\n");
        output.push_str("    mov rdi, rax\n");
        output.push_str("    call exit\n\n");

        output.push_str("exit:\n");
        output.push_str("    mov rax, 60\n");
        output.push_str("    syscall\n");

        if !self.string_literals.is_empty() {
            output.push_str("\nsection .data\n");
            for (label, string) in &self.string_literals {
                output.push_str(&format!("{}: db {}\n", label, self.escape_string(string)));
            }
        }

        let instruction_count = output
            .lines()
            .filter(|l| {
                let t = l.trim();
                !t.is_empty()
                    && !t.starts_with(';')
                    && !t.starts_with("section")
                    && !t.starts_with("global")
                    && !t.ends_with(':')
            })
            .count();

        super::CodegenResult {
            assembly: output,
            registers_used: vec![],
            frame_size: self.stack_size,
            instruction_count,
        }
    }

    fn generate_function(&mut self, func: &FunctionIR) -> String {
        let mut output = String::new();

        output.push_str(&format!("{}:\n", func.name));
        output.push_str("    push rbp\n");
        output.push_str("    mov rbp, rsp\n");

        self.var_offsets.clear();

        let param_regs = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"];
        let mut param_offset = 16;
        for (i, (param_name, _)) in func.parameters.iter().enumerate() {
            if i < param_regs.len() {
                output.push_str(&format!(
                    "    mov [rbp+{}], {}\n",
                    param_offset, param_regs[i]
                ));
            }
            self.var_offsets.insert(param_name.clone(), param_offset);
            param_offset += 8;
        }

        let mut local_offset = 8;
        for (name, _) in &func.locals {
            self.var_offsets.insert(name.clone(), -local_offset);
            local_offset += 8;
        }

        let mut max_temp = 0;
        for block in func.blocks.values() {
            for instr in &block.instructions {
                match instr {
                    IRInstruction::Add(dest, _, _)
                    | IRInstruction::Sub(dest, _, _)
                    | IRInstruction::Mul(dest, _, _)
                    | IRInstruction::Div(dest, _, _)
                    | IRInstruction::Mod(dest, _, _)
                    | IRInstruction::Move(dest, _)
                    | IRInstruction::Load(dest, _)
                    | IRInstruction::Call(dest, _, _) => {
                        if let Operand::Temporary(name) = dest {
                            let num: i32 = name[1..].parse().unwrap_or(0);
                            if num > max_temp {
                                max_temp = num;
                            }
                        }
                    }
                    _ => {}
                }
                for op in instr.operands() {
                    if let Operand::Temporary(name) = op {
                        let num: i32 = name[1..].parse().unwrap_or(0);
                        if num > max_temp {
                            max_temp = num;
                        }
                    }
                }
            }
        }

        let locals_size = local_offset - 8;
        let temps_size = max_temp * 8;
        let total_size = locals_size + temps_size;

        if total_size > 0 {
            let aligned_size = (total_size + 15) & !15;
            output.push_str(&format!("    sub rsp, {}\n", aligned_size));
            self.stack_size = aligned_size as usize;
        }

        let mut blocks: Vec<&String> = func.blocks.keys().collect();
        blocks.sort();

        for block_label in blocks {
            if let Some(block) = func.blocks.get(block_label) {
                let has_content = block
                    .instructions
                    .iter()
                    .any(|i| !matches!(i, IRInstruction::Label(_)));

                if has_content && block_label != &func.entry_block {
                    output.push_str(&format!(
                        "\n{}:\n",
                        self.operand_to_string(&Operand::Label(block_label.clone()))
                    ));
                }

                for instr in &block.instructions {
                    let asm = self.generate_instruction(instr);
                    if !asm.is_empty() && !asm.trim().starts_with(';') {
                        output.push_str(&asm);
                    }
                }
            }
        }

        let has_return = func
            .blocks
            .values()
            .flat_map(|b| b.instructions.iter())
            .any(|i| matches!(i, IRInstruction::Return(_)));

        if !has_return {
            if total_size > 0 {
                let aligned_size = (total_size + 15) & !15;
                output.push_str(&format!("    add rsp, {}\n", aligned_size));
            }
            output.push_str("    pop rbp\n");
            output.push_str("    ret\n");
        }

        output
    }

    fn generate_instruction(&mut self, instr: &IRInstruction) -> String {
        match instr {
            IRInstruction::Move(dest, src) => {
                let dest_str = self.operand_to_string(dest);
                let src_str = self.operand_to_string(src);

                if dest_str.starts_with('[') {
                    if src_str.parse::<i32>().is_ok() || src_str == "0" || src_str == "1" {
                        format!("    mov qword {}, {}\n", dest_str, src_str)
                    } else if src_str.starts_with('[') {
                        format!(
                            "    mov rax, qword {}\n    mov qword {}, rax\n",
                            src_str, dest_str
                        )
                    } else {
                        format!("    mov qword {}, {}\n", dest_str, src_str)
                    }
                } else if src_str.starts_with('[') {
                    format!("    mov {}, qword {}\n", dest_str, src_str)
                } else {
                    format!("    mov {}, {}\n", dest_str, src_str)
                }
            }
            IRInstruction::Return(Some(val)) => {
                format!(
                    "    mov rax, {}\n    mov rsp, rbp\n    pop rbp\n    ret\n",
                    self.operand_to_string(val)
                )
            }
            IRInstruction::Return(None) => "    mov rsp, rbp\n    pop rbp\n    ret\n".to_string(),
            IRInstruction::Add(dest, left, right) => self.gen_binop("add", dest, left, right),
            IRInstruction::Sub(dest, left, right) => self.gen_binop("sub", dest, left, right),
            IRInstruction::Mul(dest, left, right) => self.gen_binop("imul", dest, left, right),
            IRInstruction::Div(dest, left, right) => {
                let right_str = self.operand_to_string(right);
                let right_with_size = if right_str.starts_with('[') {
                    format!("qword {}", right_str)
                } else {
                    right_str
                };
                format!(
                    "    mov rax, {}\n    cdq\n    idiv {}\n    mov {}, rax\n",
                    self.operand_to_string(left),
                    right_with_size,
                    self.operand_to_string(dest)
                )
            }
            IRInstruction::Mod(dest, left, right) => {
                let right_str = self.operand_to_string(right);
                let right_with_size = if right_str.starts_with('[') {
                    format!("qword {}", right_str)
                } else {
                    right_str
                };
                format!(
                    "    mov rax, {}\n    cdq\n    idiv {}\n    mov {}, rdx\n",
                    self.operand_to_string(left),
                    right_with_size,
                    self.operand_to_string(dest)
                )
            }
            IRInstruction::Jump(label) => {
                format!("    jmp {}\n", self.operand_to_string(label))
            }
            IRInstruction::JumpIf(cond, label) => {
                let cond_str = self.operand_to_string(cond);
                if cond_str.starts_with('[') {
                    format!(
                        "    cmp qword {}, 0\n    jnz {}\n",
                        cond_str,
                        self.operand_to_string(label)
                    )
                } else {
                    format!(
                        "    cmp {}, 0\n    jnz {}\n",
                        cond_str,
                        self.operand_to_string(label)
                    )
                }
            }

            IRInstruction::JumpIfNot(cond, label) => {
                let cond_str = self.operand_to_string(cond);
                if cond_str.starts_with('[') {
                    format!(
                        "    cmp qword {}, 0\n    jz {}\n",
                        cond_str,
                        self.operand_to_string(label)
                    )
                } else {
                    format!(
                        "    cmp {}, 0\n    jz {}\n",
                        cond_str,
                        self.operand_to_string(label)
                    )
                }
            }
            IRInstruction::Label(label) => {
                format!("{}:\n", self.operand_to_string(label))
            }
            IRInstruction::Call(dest, func, args) => self.gen_call(dest, func, args),
            IRInstruction::CmpEq(dest, left, right) => self.gen_cmp("sete", dest, left, right),
            IRInstruction::CmpNe(dest, left, right) => self.gen_cmp("setne", dest, left, right),
            IRInstruction::CmpLt(dest, left, right) => self.gen_cmp("setl", dest, left, right),
            IRInstruction::CmpLe(dest, left, right) => self.gen_cmp("setle", dest, left, right),
            IRInstruction::CmpGt(dest, left, right) => self.gen_cmp("setg", dest, left, right),
            IRInstruction::CmpGe(dest, left, right) => self.gen_cmp("setge", dest, left, right),
            IRInstruction::Load(dest, addr) => {
                format!(
                    "    mov {}, [{}]\n",
                    self.operand_to_string(dest),
                    self.operand_to_string(addr)
                )
            }
            IRInstruction::Store(addr, src) => {
                let addr_str = self.operand_to_string(addr);
                let src_str = self.operand_to_string(src);
                if addr_str.starts_with('[') {
                    format!("    mov qword {}, {}\n", addr_str, src_str)
                } else {
                    format!("    mov [{}], {}\n", addr_str, src_str)
                }
            }
            _ => String::new(),
        }
    }

    fn gen_binop(&mut self, op: &str, dest: &Operand, left: &Operand, right: &Operand) -> String {
        let left_str = self.operand_to_string(left);
        let right_str = self.operand_to_string(right);
        let dest_str = self.operand_to_string(dest);

        let right_with_size = if right_str.starts_with('[') {
            format!("qword {}", right_str)
        } else {
            right_str
        };

        if left_str.starts_with('[') {
            format!(
                "    mov rax, qword {}\n    {} rax, {}\n    mov {}, rax\n",
                left_str, op, right_with_size, dest_str
            )
        } else {
            format!(
                "    mov rax, {}\n    {} rax, {}\n    mov {}, rax\n",
                left_str, op, right_with_size, dest_str
            )
        }
    }

    fn gen_cmp(&mut self, set_op: &str, dest: &Operand, left: &Operand, right: &Operand) -> String {
        let left_str = self.operand_to_string(left);
        let right_str = self.operand_to_string(right);
        let dest_str = self.operand_to_string(dest);

        let mut output = String::new();

        if left_str.starts_with('[') && right_str.starts_with('[') {
            output.push_str(&format!("    mov rax, qword {}\n", left_str));
            output.push_str(&format!("    cmp rax, qword {}\n", right_str));
        } else if left_str.starts_with('[') {
            output.push_str(&format!("    cmp qword {}, {}\n", left_str, right_str));
        } else if right_str.starts_with('[') {
            output.push_str(&format!("    cmp {}, qword {}\n", left_str, right_str));
        } else {
            output.push_str(&format!("    cmp {}, {}\n", left_str, right_str));
        }

        output.push_str(&format!("    {} al\n", set_op));

        output.push_str(&format!("    movzx rax, al\n"));
        output.push_str(&format!("    mov {}, rax\n", dest_str));

        output
    }

    fn gen_call(&mut self, dest: &Operand, func: &Operand, args: &[Operand]) -> String {
        let mut output = String::new();

        output.push_str("    push rcx\n    push rdx\n    push rsi\n    push rdi\n");
        output.push_str("    push r8\n    push r9\n    push r10\n    push r11\n");

        let regs = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"];
        for (i, arg) in args.iter().enumerate() {
            if i < 6 {
                output.push_str(&format!(
                    "    mov {}, {}\n",
                    regs[i],
                    self.operand_to_string(arg)
                ));
            } else {
                output.push_str(&format!("    push {}\n", self.operand_to_string(arg)));
            }
        }

        output.push_str(&format!("    call {}\n", self.operand_to_string(func)));

        if args.len() > 6 {
            output.push_str(&format!("    add rsp, {}\n", (args.len() - 6) * 8));
        }

        output.push_str(&format!("    mov {}, rax\n", self.operand_to_string(dest)));

        output.push_str("    pop r11\n    pop r10\n    pop r9\n    pop r8\n");
        output.push_str("    pop rdi\n    pop rsi\n    pop rdx\n    pop rcx\n");

        output
    }

    fn operand_to_string(&mut self, op: &Operand) -> String {
        match op {
            Operand::Variable(name) => {
                if let Some(offset) = self.var_offsets.get(name) {
                    if *offset > 0 {
                        format!("[rbp+{}]", offset)
                    } else {
                        format!("[rbp-{}]", -offset)
                    }
                } else {
                    format!("[rbp-8]")
                }
            }
            Operand::Temporary(name) => {
                let temp_num: i32 = name[1..].parse().unwrap_or(0);
                let locals_size = self.var_offsets.len() * 8;
                let offset = locals_size + (temp_num as usize) * 8;
                format!("[rbp-{}]", offset)
            }
            Operand::Label(name) => name.clone(),
            Operand::IntLiteral(v) => v.to_string(),
            Operand::FloatLiteral(v) => v.to_string(),
            Operand::BoolLiteral(v) => if *v { "1" } else { "0" }.to_string(),
            Operand::StringLiteral(s) => {
                let label = format!(".L.str{}", self.string_counter);
                self.string_counter += 1;
                self.string_literals.push((label.clone(), s.clone()));
                label
            }
            Operand::MemoryAddress { base, offset } => {
                if *offset == 0 {
                    format!("[{}]", base)
                } else if *offset > 0 {
                    format!("[{}+{}]", base, offset)
                } else {
                    format!("[{}-{}]", base, -offset)
                }
            }
        }
    }

    fn escape_string(&self, s: &str) -> String {
        let mut escaped = String::new();
        for c in s.chars() {
            match c {
                '"' => escaped.push_str("\\\""),
                '\\' => escaped.push_str("\\\\"),
                '\n' => escaped.push_str("\\n"),
                '\r' => escaped.push_str("\\r"),
                '\t' => escaped.push_str("\\t"),
                _ => escaped.push(c),
            }
        }
        format!("\"{}\"", escaped)
    }
}

impl Default for X86Generator {
    fn default() -> Self {
        Self::new()
    }
}
